### ISSUE TITLE
Bouton réclamation

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#13]
Corriger l'orthographe sur le bouton "Ajouter une réclamation"

**Comment by aminekehlimoussab** [comment]
- Correction de l'orthographe sur le bouton " Ajouter une réclamation "

**Comment by Mounia-kazi** [comment]
Ce n'est toujours pas réglé chez moi.

**Comment by aminekehlimoussab** [comment]
c'est fait
