### ISSUE TITLE
Menu principal

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#14]
- Enlever "Main navigation" ou bien la traduire en français.

- Mettre des majuscules aux premiers mots des quatre premiers éléments du menu.

- Le quatrième élément dépasse le menu voir comment remédier à cela.

**Comment by aminekehlimoussab** [comment]
- Remplacement de " MAIN NAVIGATION "   par   " MENU PRINCIPAL ".
- Les majuscules sur les quartes premiers éléments du menu
- Un saut de ligne dans le quatrième élément du menu
