### ISSUE TITLE
Authentification cas d'erreur

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#15]
Lors de la saisie de mot de passe et/ou d'identifiant incorrects mettre le message d'erreur en rouge et juste en dessous ou juste au dessus des champs à saisir.
Aussi, corriger dans le message d'erreur le mot "incorrect" .

**Comment by aminekehlimoussab** [comment]
La position et la couleur du message d'erreur a été modifié

**Comment by Mounia-kazi** [comment]
Pourquoi j'ai le message "Vous avez pas assez de droit pour accéder a cette plateforme" quand l'dientifiant est erroné ?
