### ISSUE TITLE
Preuve de livraison KO

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#24]
Le code ne se charge pas et aucune info n'est enregistrée lors de la validation.

**Comment by aminekehlimoussab** [comment]
les problèmes de la preuve de livraison sont réglés
- Chargement des informations de client expéditeur ( Nom , Prénom , Email )
- L'envoi de l'email avec la photo de la signature 
- Affichage de message de confirmation de l'envoi de l'email
