### ISSUE TITLE
Ajout d'agence "Gestion des localités"

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#29]
Affichage d'une sorte d'alerte avec un message "rien" et un bouton "ok" lorsqu'on choisit la ville sur la liste

**Comment by aminekehlimoussab** [comment]
Le message d’alerte  a été enlevé ,

**Comment by salimKazi** [comment]
Le message d'alerte est toujours là

**Comment by aminekehlimoussab** [comment]
tu peux vérifier le message maintenant
