### ISSUE TITLE
Page d'erreurs "Modification d'une agence"

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#32]
Lors de l'introduction d'un caractère au lieu d'un nombre dans la partie "Numéro de rue" cela génère une page remplie d'erreurs et de codes. 
Même chose pour l'introduction de caractères au lieu des chiffres dans la case "Code postal".

**Comment by aminekehlimoussab** [comment]
c'est réglé, j'ai fait un filtre sur les caractères saisis, donc les champs "  Numéro de rue " et "Code postal" n’acceptent que des nombres

**Comment by salimKazi** [comment]
La page ne génère plus d'erreurs mais après une recherche "erroné", on obtient une page vide au lieu d'un tableau vide (sans paramètres) (le résultat attendu)

**Comment by aminekehlimoussab** [comment]
c'est réglé
