### ISSUE TITLE
Amélioration "Gestion des secteurs d'activités"

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#41]
Centrer les éléments du tableau de la liste des secteurs d'activités pour avoir un meilleur affichage de nos données et une meilleure lisibilité des éléments.
Mettre les nombres d'agents affectés et le nombre de communes en souligné pour préciser que ce sont des liens et que l'utilisateur puisse remarquer cela.
Transformer les boutons (modifier, supprimer, affecter) en icônes pour avoir un affichage d'interface moins encombrant et plus moderne.

**Comment by aminekehlimoussab** [comment]
c'est fait
