### ISSUE TITLE
Modification "Activité agents"

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#51]
Mettre "valider" au lieu de "Terminer" dans le bouton de validation de modification de l'activité".
L'affichage du bas de la page "Eurequat-algérie", version 1.0 et "2016" est désordonné au début, mais en redimensionnant  la fenêtre, puis on la rend plus large, l'affichage devient meilleur(problème de résolution peut être)

**Comment by aminekehlimoussab** [comment]
c'est fait

**Comment by salimKazi** [comment]
Pour le bouton, oui, reste plus que la résolution (bas de page)

**Comment by aminekehlimoussab** [comment]
normalement le problème est réglé

**Comment by salimKazi** [comment]
L'affichage du bas de page (modification "activité agents") est toujours désordonné (la signature)

**Comment by aminekehlimoussab** [comment]
c'est corrigé
