### ISSUE TITLE
Amélioration "Réclamation client"

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#54]
Transformer les boutons en icônes dans la page pour avoir un affichage moins encombrant et plus moderne.                                                     
Mettre plus en évidence le bouton d'ajout d'une réclamation.   
Centrer les éléments du tableau (les noms des clients, motifs d'appels... etc)

**Comment by aminekehlimoussab** [comment]
c'est fait
