### ISSUE TITLE
Nombres pages (Activités agents)

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#57]
Mettre les numéros de page (lien et nombre) en dehors du tableau  de la liste des activités

**Comment by aminekehlimoussab** [comment]
c'est fait

**Comment by salimKazi** [comment]
ça serait plus visible de la mettre en haut à droite.

**Comment by aminekehlimoussab** [comment]
je pense que généralement les boutons de pagination se positionne en bas de tableau

**Comment by salimKazi** [comment]
Oui, même l'affichage s'est amélioré( juste que pour le positionnement de la pagination soit dans le même endroit pour toutes les pages de l'application)
