### ISSUE TITLE
Ajout réclamation 

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#6]
Ajout de réclamation sans remplir aucun champs.

**Comment by youssouf1989** [comment]
c'est réglé

**Comment by Mounia-kazi** [comment]
En remplissant tous les champs obligatoires un message d'erreur d'affiche pour me m'indiquer qu'il faut remplir tout les champs obligatoires.

**Comment by aminekehlimoussab** [comment]
c'est fait
