### ISSUE TITLE
Heure des événements

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#65]
Mettre l'heure des différents événements (prélèvement, envoi)

**Comment by aminekehlimoussab** [comment]
c'est fait , la modification est faite au niveau de l'application Mobile
et voici un exemple de code colis : 170express7463

**Comment by salimKazi** [comment]
Dernier soucis, l'heure par exemple s'affiche 12:8 au lieu de 12:08

**Comment by aminekehlimoussab** [comment]
le problème est réglé , je vais t'envoyer la version à jour de l'application mobile une fois que je termine les modifications nécessaires
