### ISSUE TITLE
Preuve de livraison 

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#7]
Impossible de saisir les champs : Nom, Prénom et chemin.

**Comment by Mounia-kazi** [comment]
Pourquoi il y a un un bouton "valider" devant code bordereau et un bouton "Envoyer" ?

**Comment by aminekehlimoussab** [comment]
le bouton " valider " c'est pour charger les informations de colis de la base de donnée,  tu met un code bordereau dans le champ après quand tu valide, les informations de colis se charge dans le formulaire , et pour envoyer la preuve de livraison tu fait " envoyer "

**Comment by Mounia-kazi** [comment]
d'accord.

**Comment by Mounia-kazi** [comment]
Mettre "Charger" à la place de "valider"

**Comment by aminekehlimoussab** [comment]
c'est fait

**Comment by aminekehlimoussab** [comment]
c'est réglé
