### ISSUE TITLE
Suivi de livraison

### ISSUE THREAD

**Issue by salimKazi** [aminekehlimoussab/TrakinBackOffice2#72]
Ajouter une colonne "agent" dans le tableau du suivi de livraison

**Comment by aminekehlimoussab** [comment]
c'est fait,
concernant la phrase " l'agent n'existe plus ", c'est parce que l'agent a été supprimé de la base de donnée, donc ses information (nom et prénom de l'agent ) n'existe pas

**Comment by salimKazi** [comment]
Peut-on remplacer "l'agent n'existe plus" par une icone ou un "/"?

**Comment by aminekehlimoussab** [comment]
c'est fait
