### ISSUE TITLE
Suivi de livraison 

### ISSUE THREAD

**Issue by Mounia-kazi** [aminekehlimoussab/TrakinBackOffice2#8]
Corriger : réception et enlèvement.

**Comment by aminekehlimoussab** [comment]
La correction est faite

**Comment by Mounia-kazi** [comment]
Corriger prélèvement également.

**Comment by aminekehlimoussab** [comment]
la Correction de prélèvement est faite

**Comment by Mounia-kazi** [comment]
Le champ "chemin" est inaccessible aussi on ne reçois pas les mails
